### PR TITLE
Fix compilation error in src/gsibec/gsigeos/m_read_geosens.F90

### LINKED ISSUE #51: Build errors of gsibec 1.1.1 with gfortran 11.3.0
Getting the following error multiple times when compiling gsibec 1.1.1 on macOS with clang 13.1.6 and gfortran 11.3.0:
```
/Users/heinzell/work/spack-stack/spack-stack-1.3.1/cache/build_stage/spack-stage-gsibec-1.1.1-hwumm5navc2eqa7u7roxurh46tpgojy3/spack-src/src/gsibec/gsigeos/m_read_geosens.F90:162:18:

   85 |            call read_(ns,nprocs(ii))
      |                                    2
......
  162 |              ii =0
      |                  1
Error: Index variable 'ii' redefined at (1) in procedure 'read_' called from within DO loop at (2)
/Users/heinzell/work/spack-stack/spack-stack-1.3.1/cache/build_stage/spack-stage-gsibec-1.1.1-hwumm5navc2eqa7u7roxurh46tpgojy3/spack-src/src/gsibec/gsigeos/m_read_geosens.F90:165:26:

   85 |            call read_(ns,nprocs(ii))
      |                                    2
......
  165 |                 ii = ii +1
      |                          1
```

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Fix compilation error in `src/gsibec/gsigeos/m_read_geosens.F90` with gfortran 11.3.0: use `jj` instead of `ii` in subroutine `read_`

## Issues

This should fix https://github.com/GEOS-ESM/GSIbec/issues/51.

This branch compiles on my macOS where 1.1.1 aborted with the compilation error reported in the issue.

### CODE REVIEW

**Review by rtodling — APPROVED** [review]

**Comment by rtodling** [comment]
It's in develop now.

**Comment by climbfuji** [comment]
Thanks @rtodling! Can this go into the next release 1.1.2 ? We'd need that to role out the new spack-stack.
