### PR TITLE
Fix incorrect use of ii in m_read_geosens.F90

### LINKED ISSUE #51: Build errors of gsibec 1.1.1 with gfortran 11.3.0
Getting the following error multiple times when compiling gsibec 1.1.1 on macOS with clang 13.1.6 and gfortran 11.3.0:
```
/Users/heinzell/work/spack-stack/spack-stack-1.3.1/cache/build_stage/spack-stage-gsibec-1.1.1-hwumm5navc2eqa7u7roxurh46tpgojy3/spack-src/src/gsibec/gsigeos/m_read_geosens.F90:162:18:

   85 |            call read_(ns,nprocs(ii))
      |                                    2
......
  162 |              ii =0
      |                  1
Error: Index variable 'ii' redefined at (1) in procedure 'read_' called from within DO loop at (2)
/Users/heinzell/work/spack-stack/spack-stack-1.3.1/cache/build_stage/spack-stage-gsibec-1.1.1-hwumm5navc2eqa7u7roxurh46tpgojy3/spack-src/src/gsibec/gsigeos/m_read_geosens.F90:165:26:

   85 |            call read_(ns,nprocs(ii))
      |                                    2
......
  165 |                 ii = ii +1
      |                          1
```

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Bug fix in `src/gsibec/gsigeos/m_read_geosens.F90`: use `jj` instead of `ii` in subroutine `read_`

## Issues

This should fix https://github.com/GEOS-ESM/GSIbec/issues/51.

This branch compiles on my macOS where 1.1.1 aborted with the compilation error reported in the issue.

### CODE REVIEW

**Comment by climbfuji** [comment]
@rtodling @danholdaway FYI

**Review by danholdaway — APPROVED** [review]
Given there's an implicit none for the module I wonder why this compiled on any platform?

**Review by rtodling — COMMENTED** [review]
Sorry this fix is an over kill! All that is needed in the original code is for ii to be declared!

Can that be changed as such?

R

**Comment by climbfuji** [comment]
> Sorry this fix is an over kill! All that is needed in the original code is for ii to be declared!
> 
> Can that be changed as such?
> 
> R

Sure, trying this now. Going to add `implicit none` in `read_` as well (if it works)

**Comment by rtodling** [comment]
> Given there's an implicit none for the module I wonder why this compiled on any platform?

I am looking at this more closely. There is NO ERROR in the original code. The variable ii is declared in line 50 of the main routine. The routine the change was made from ii to jj is a contained routine in the main routine ... therefore it inherits the variable declaration. That is why the code compiles ... because the there is no error.

Now what is likely happening is that there a pick compiler out that does not like variables declared in the main routine when they are used in the contained codes ... that would be a problem in the compiler.

**Comment by climbfuji** [comment]
It's very much irrelevant if the code is correct or not, gcc 11.3 is not something we can avoid ...

Please see if https://github.com/GEOS-ESM/GSIbec/pull/53 is acceptable.

**Comment by climbfuji** [comment]
Better solution was merged (#53) thanks @rtodling for your suggestion.
